name: Push Local Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  push_image:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu environment
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Use an assumed role for AWS credentials
          role-session-name: github-actions
          aws-region: us-east-1  # Specify your AWS region

      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1  # Action to authenticate to Amazon ECR
        with:
          region: us-east-1  # Specify your AWS region

      - name: Build Docker Image
        run: |
          docker build -t testecr:latest ./  # Build the image with the correct tag (testecr:latest)
      
      - name: Tag Docker Image for ECR
        run: |
          docker tag testecr:latest public.ecr.aws/m0h2p2z6/testecr:latest  # Tag it for ECR

      - name: Push Docker Image to Amazon ECR Public
        run: |
          docker push public.ecr.aws/m0h2p2z6/testecr:latest  # Push the correctly tagged image to ECR
####